In [1]:
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
print(a.shape)

(3, 4)


In [ ]:
print(a.dtype)

int32


In [7]:
print(a.size)

12
